### ISSUE TITLE
Lag time between selecting "Delete" and the entity actually being deleted

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#2925] opened 2020-05-19 23:51 UTC
Issue reported from Uwazi user:

> In general, there seems to be a synchronization lag across different components. For example, after deleting a Document entity, it continued to appear for several minutes as an option that could be linked to when creating a new Act.

**Comment by txau** [comment] 2020-07-25 20:22
This needs more detailed steps to reproduce the issue. I tried the workflow described and the deletion is instantaneous. This could happen due to a misconfiguration of the research interval in elasticsearch or just casual server lag. Maybe due to working on several tabs and a particular combination of steps. Closing for now.

**Closed by txau** 2020-07-25 20:22 UTC
Labels: Bug
