### ISSUE TITLE
System Validation Problem

### ISSUE THREAD

**Issue by ElvisCos** [huridocs/uwazi#2489] opened 2019-08-23 13:30 UTC
Hello, 
I was organizing a document in it's respective grouping but it the system fails to save it. I end up receiving the following response that is displayed in the photo. 
Any help that could be advanced will be highly appreciated. 
@hsips 

![Screenshot (127)](https://user-images.githubusercontent.com/53751774/63595660-28c77b80-c5c2-11e9-8da7-506e36257f2c.png)

**Comment by habbes** [comment] 2019-08-23 16:27
@ElvisCos could you check whether you have duplicate values in that list?

**Comment by HSips** [comment] 2019-08-24 05:36
@habbes Just checked. Nope. Its a new value.

**Comment by HSips** [comment] 2019-08-24 05:58
Also happening in more than 1 thesaurus list. This one in 'themes'
@ElvisCos @habbes 
![240819](https://user-images.githubusercontent.com/22650647/63633220-45f55c00-c64d-11e9-8d80-604b20ada978.png)

**Comment by daneryl** [comment] 2019-08-26 07:39
@HSips there is duplicated values, we need to improve the feedback on this, for the 'Themes' Thesauri here is a list of duplicated values:

- "Chad"
- "Diego Garcia"
- "Information and Communication Technologies (ICTs)"
- "Military Staff Committee (MSC)"
- "Niger"
- "Pharmaceutical Manufacturing Plan for Africa (PMPA)"
- "Tanzania"
- "UNSC Resolution 1569 (2004)"
- "Youth"

**Comment by HSips** [comment] 2019-09-03 03:20
@daneryl @habbes @ElvisCos sorry for delayed response on this.
I understand that the duplications are creating the validation problem? Yes, the 'Themes' list needs cleaning up to eliminate duplications, but I suspect there are no duplications in the 'AU PSC meetings' thesaurus.
I will turn my attention to cleaning up duplicates in 'themes'

**Comment by txau** [comment] 2019-09-03 16:09
@HSips there is an option for sorting the thesaurus alphabetically. That may help spot duplicated entries.

**Comment by HSips** [comment] 2019-09-04 03:09
@txau thanks! will do.

**Comment by HSips** [comment] 2019-09-04 03:54
Tried to make corrections/additions to 'Themes' and 'PSC Meetings' thesauri respectively and still brings up 'validation failed'. Please see screenshots below @ElvisCos 

![040919-2](https://user-images.githubusercontent.com/22650647/64224610-dac74780-cee0-11e9-92ee-589993fe4319.png)
![040919-1](https://user-images.githubusercontent.com/22650647/64224611-db5fde00-cee0-11e9-977d-6d517ccd5190.png)

**Comment by daneryl** [comment] 2019-09-10 11:10
@hsips, tries the same and it worked for me, @txau, @RafaPolit what do we do about this ? 

- implement pretty printing errors ?
- implement client validation also ?
- remove duplicate validation assuming the risks ?

**Comment by txau** [comment] 2019-09-10 13:30
@daneryl "Validation error" does means there are duplicates? or other errors as well?

**Comment by daneryl** [comment] 2019-09-13 09:10
@txau yeah it can be any error.

**Comment by txau** [comment] 2019-09-13 14:14
@daneryl I guess it makes sense to print a pretty error if the error is telling the user exactly what is going on? Particularly if the problem is duplication, even which ones are duplicated?

**Comment by daneryl** [comment] 2019-09-16 07:48
@txau yes it makes sense, we should #2490 can we close this ?

**Comment by txau** [comment] 2019-09-16 14:27
@daneryl yes

**Comment by daneryl** [comment] 2019-10-18 07:43
@txau this was mostly because of duplication thesauri error, we just removed that validation #2586, can we close this ?

**Comment by txau** [comment] 2019-10-21 13:24
@daneryl Yes. Closing.

**Closed by txau** 2019-10-21 13:24 UTC
