### ISSUE TITLE
Demo instance: 504 Gateway Time-out

### ISSUE THREAD

**Issue by YolandaCHR** [huridocs/uwazi#417] opened 2016-09-14 12:34 UTC
Problems with uploading documents on our demo instance - getting the following message:

**504 Gateway Time-out**
nginx

**Comment by txau** [comment] 2016-09-15 11:34
Hi @YolandaCHR ,

We've tested this several times ourselves and we were not able to reproduce the error. Could you please provide more information?

- What browser were you using?
- Did you try this only once or several times?
- Was this happening with different documents or always the same one?
- Did you experience this bug at a particular moment (this could be a momentary network or server malfunction) or this has been happening consistently at different moments in time?

**Comment by YolandaCHR** [comment] 2016-09-15 12:47
I have now tried it today and it seems to be working fine again.the error was on both Firefox and Chrome, yesterday - with a very small document. It might be that it could be something with our connection here on campus - not sure.

Apologies for the false alarm! All looks fine again in Chrome

*Firefox does not upload on my side, but no error either

**Comment by txau** [comment] 2016-09-15 18:40
@YolandaCHR we are releasing an update soon that may fix some of these glitches. I'm leaving the issue open so we can revisit it after the release.

**Comment by txau** [comment] 2017-01-25 16:11
We haven't had wild 504 in a while now. They were mostly related to connectivity issues between the different servers of the platform (load balancer, database, web server). Closing.

**Closed by txau** 2017-01-25 16:11 UTC
Labels: NEW
