### ISSUE TITLE
Cannot add new properties to a document template

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#868] opened 2017-03-17 16:05 UTC
I created a document template on https://sacls.uwazi.io called "General Document Template". I added a few fields to it and it was working fine. I uploaded a few documents using that template, and now when I go back to the template to add another field, it won't let me drag-drop any of the property options. Nothing moves when I select it. I wanted to add a new connection using the 'select' property type. 

![image](https://cloud.githubusercontent.com/assets/354426/24051797/b128d49a-0b09-11e7-9de8-1c85fd6b5908.png)

**Comment by kjantin** [comment] 2017-03-17 16:31
Now it's working again. Maybe it's working because all the documents are published?

**Comment by txau** [comment] 2017-03-20 11:26
@kjantin I tried to reproduce the bug following your steps without luck. Since you also reported is working again, lets close this for now and reopen if it happens again and we can reproduce. It may have been a connection problem or similar.

**Closed by txau** 2017-03-20 11:26 UTC
Labels: bug, NEW
