### ISSUE TITLE
Cannot select more than one Instruments on "Rights Alleged to be Violated"

### ISSUE THREAD

**Issue by Fabriel1** [huridocs/uwazi#1798] opened 2018-07-24 15:24 UTC
Hello, 
Under the Property of "Rights Alleged to be violated", the Select List does not give us the option of selecting more than one Item. Consequently, this has made it impossible to tag other Instruments' provisions, aside the ACHPR provisions that are given reference to - in terms of articles violated.
![capture 1](https://user-images.githubusercontent.com/33451614/43148526-fecb8d20-8f54-11e8-95b6-fc9841ec3cfc.JPG)
![capture 2](https://user-images.githubusercontent.com/33451614/43148528-fefb094c-8f54-11e8-82ac-18930b4f5e52.JPG)

**Comment by txau** [comment] 2018-07-24 22:21
Hello @Fabriel1, I'm not sure I'm understanding what the problem is. 

Select and multi-select only support one thesaurus. If you need all options from two thesaurus combined, you should create a dictionary combining these two options.

If the thesauri is too big, you can always organize it in groups so its more usable: https://github.com/huridocs/uwazi/wiki/Create-thesauri#nested-options-in-thesauri

**Comment by txau** [comment] 2018-08-02 17:53
@Fabriel1 closing until further notice. Please reopen if needed.

**Closed by txau** 2018-08-02 17:53 UTC
