### ISSUE TITLE
The "No type" filter in uploads is not working as expected

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#1162] opened 2017-07-20 16:36 UTC
## To reproduce

- Add a document (not entity!) in uploads, without assigning a type
- **First bug**: the aggregations list in the right should update to show at least 1 "No type" document, instead, it still shows 0 (or the previous number)
- Try to filter only the "No type" documents
- **Second bug**: You get a server error in the response

**Comment by daneryl** [comment] 2017-07-31 16:32
fixed only the second part on #1185.
i think the first part its not a bug but a feature we never implemented, it is hard to come to a solution to this beacauso of how near-real time elasticsearch works. we should discuss/fix that on a separate issue: #1187

**Closed** 2017-08-04 09:29 UTC
Labels: Status: Sprint, Type: Bug
