### ISSUE TITLE
Document stuck in "processing..."

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#4248] opened 2022-02-07 13:41 UTC
Find out if this is caused by a bug. The document seems to have been processed alright.

(CEJIL)
![image](https://user-images.githubusercontent.com/489831/152798941-e51e7c74-a27d-4350-aece-67bee7051c09.png)

**Comment by txau** [comment] 2022-04-05 04:39
Apparently this is a recurring issue that could not be replicated in the past: https://github.com/huridocs/uwazi/issues/3148

**Comment by Zasa-san** [comment] 2022-07-20 19:15
Could happen if the processing finishes while the users is not on the library. This seems to be related to the store not being properly updated. 
A simple way to reproduce is:
- Adding a delay to `app/api/files/processDocument.ts`
- Uploading a file
- Navigating to settings or an entity view
- Returning to the library

The document will display as ready, but the card and upload button will remain in `processing`.

Another scenario involves reloading or navigating when the file is being processed, an the processing of the file fails.

These statuses for the button and the card are being updated by a socket with the listeners are in the components, they might be unmounted when the emit happens. This means that the functions that update the store may not trigger as well, since the component missed the socket event.

**Comment by txau** [comment] 2022-07-21 01:42
@Zasa-san if I am understanding correctly, the server side process won't update the document status if the user does not receive the event via socket?

**Comment by Zasa-san** [comment] 2022-07-21 13:46
@txau Yes. For example:
https://github.com/huridocs/uwazi/blob/18db7a95e2766ab266244aafac6116b1c712dc0c/app/react/Metadata/components/UploadButton.js#L38-L40

Those actions update the store, but the component might not be mounted when the socket emits.

**Comment by txau** [comment] 2022-07-21 16:13
@Zasa-san my question is if the document remains as "Processing" in the database, because the problem here is not with the UI, the document appears as processing with a fresh session as well.

**Comment by Zasa-san** [comment] 2022-07-21 17:55
@txau That, I was not able to reproduce. I've not gotten a document stuck in `processing`in the DB.
The original issue https://github.com/huridocs/uwazi/issues/3148 state that a refresh fixes the problem, that's indicating that the document is not stuck in processing in the DB. Are there instances where even a refresh doesn't fix the problem?
https://github.com/huridocs/uwazi/pull/4884 Should fix the UI side of things that prevents the UI from updating.

**Comment by txau** [comment] 2022-07-21 18:03
here you have an example:  https://summa.cejil.org/en/library/?q=(allAggregations:!f,filters:(),from:0,includeUnpublished:!f,limit:30,order:desc,sort:creationDate,types:!(%275a4d294c79f3f44b101e2816%27),unpublished:!f)

In renders like this in the list:

![image](https://user-images.githubusercontent.com/489831/180282902-6bc07f12-69e8-4128-87e5-38af93995d2d.png)

And it shows this in the full view:

![image](https://user-images.githubusercontent.com/489831/180282948-d040f921-6bb6-42fe-90c1-042c8d280783.png)

It says "conversion failed" but the document is there and it is apparently working?

**Comment by Zasa-san** [comment] 2022-07-21 18:08
@txau I've updated my last comment before seeing your last comment. Previous to #4884 documents had no display for the `processing`status.
https://github.com/huridocs/uwazi/blob/18db7a95e2766ab266244aafac6116b1c712dc0c/app/react/Attachments/components/File.tsx#L141-L147

If while processing the document, the UI updated, the document would show as failed, until the processing is complete and the UI is refreshed. But at no point to document was truly on a `failed` state.

With #4884 we have added a `processing` status display for documents, and nothing should get 'stuck' on the UI even if you refresh or navigate away from the library.

I will try to reproduce the example above, but right now `failed` documents don't get the UI stuck on processing. It would also be great if we could check the status of the document in the DB.

**Comment by Zasa-san** [comment] 2022-07-21 21:03
@txau Doing a quick check, the file is stuck as `processing`, it shows as failed for the reasons mentioned above. The card remains as processing because, effectively, there's a file marked as processed.

I can’t find a reason why the file would have been saved as `processing`. Updating that on the DB and doing a reindex would fix the problem. Do the instances where this is happening have OCR?

**Comment by txau** [comment] 2022-07-21 21:07
@Zasa-san they do have OCR

**Comment by Zasa-san** [comment] 2022-07-22 13:25
The only way to reproduce this error was to manually stop the server while a file was being uploaded or being processed. This might be related to the fact that node will wait for connections to terminate before shutting down. So it finished the upload, closes the connection and gracefully terminates, and the processing of the file will never complete.

**Comment by txau** [comment] 2022-07-22 14:05
> The only way to reproduce this error was to manually stop the server while a file was being uploaded or being processed. This might be related to the fact that node will wait for connections to terminate before shutting down. So it finished the upload, closes the connection and gracefully terminates, and the processing of the file will never complete.

@Zasa-san it makes sense. I think we should pull this an a separate issue so it gets fixed with another strategy.

**Comment by txau** [comment] 2022-10-14 14:12
I guess we need to at least run some check/migration to fix the status of the pending documents:

![image](https://user-images.githubusercontent.com/489831/195868204-cbb124f0-645e-423d-b23f-f3190f99e262.png)

**Comment by daneryl** [comment] 2022-10-14 15:31
Create a migration to fix the current wrongly flagged "processing" files status to "ready".
Migration requires reindex, only for those tenants that have wrongly flagged files.

**Comment by Zasa-san** [comment] 2022-11-22 14:22
We agreed to check if full text property is present in the processing document, if it is we move it to ready, if not to failed. This should unstuck the doc and give users feedback.

**Closed** 2023-01-05 09:59 UTC
Labels: Bug :lady_beetle:, Sprint, Priority: High
