### ISSUE TITLE
Avoid global mocking of T for tests so we can correctly test future implementations

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#1725] opened 2018-06-25 15:33 UTC
The translation service T has been globally mocked on tests.

While handy, this prevents the correct testing of the new implementation regarding the in-line translation service.  Passing the extra parameters cannot be tested, and anyone can easily break the app.

**Comment by konzz** [comment] 2018-06-27 14:08
@RafaPolit Not sure we need this, the problem is quickly detected by e2e, but in that case was not since was a combination of two different PR and we didn't run e2e on CI that is the one with up to date branches. 
Also is true that current e2e do not have all cases and a bug may slip through, having T globally mocked is not ideal, and if you find a good solution will be great.

**Comment by txau** [comment] 2020-05-28 14:17
@konzz @RafaPolit I guess we can close this issue?

**Closed** 2021-03-02 09:59 UTC
Labels: Priority: Low, Review needed, Tech Debt
