### ISSUE TITLE
Reset source document selection when navigating away

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#320] opened 2016-08-22 12:04 UTC
1. Go into the viewer for a document
2. Select text and hit "connect to paragraph"
3. Navigate to library and open another doc
4. The new doc already has a selection with the same coordinates as the initial doc

It should reset the state without breaking the "connect to paragraph" functionality.

**Comment by konzz** [comment] 2017-02-03 15:05
Can't reproduce, probably already fixed in the recent changes to this section

**Closed by konzz** 2017-02-03 15:05 UTC
Labels: bug, dev, next
