### ISSUE TITLE
CSS module missing when building

### ISSUE THREAD

**Issue by chrisha88** [huridocs/uwazi#1495] opened 2018-03-02 11:04 UTC
Got the below error when I ran git pull and built it using Webpack.

`module.js:471
throw err;
^

Error: Cannot find module 'optimize-css-assets-webpack-plugin'
at Function.Module._resolveFilename (module.js:469:15)
at Function.Module._load (module.js:417:25)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Object. (/home/dell/uwazi/webpack.production.config.js:6:31)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)

**Comment by RafaPolit** [comment] 2018-03-08 15:08
Please follow the instructions described on your issue: #1497

And report back the result.  Also, how are you running webpack? From the internal node_modules? From a globally installed webpack?

Best regards,
Rafa.

**Comment by chrisha88** [comment] 2018-03-09 06:53
I run the following code after $ git pull on the uwazi directory
`$ webpack --config webpack.production.config.js`

**Comment by RafaPolit** [comment] 2018-03-09 16:25
Please try first updating the node modules via **yarn install**, then we will see if it is a webpack problem.

You could try using the webpack inside node_modules/bin instead of the globally installed one just to be sure this is not a versioning problem.

**Comment by chrisha88** [comment] 2018-03-09 17:34
Hi Rafa, 
I have no previous experience of Ubuntu so you may have to give me the exact code I need to type in and the sequence of codes.
Sorry for the trouble

**Comment by RafaPolit** [comment] 2018-03-09 18:20
I am guessing this is a problem with the project dependencies.

Lets get that out of the way first. So please run these commands in the project directory (each $ is a new line, do not copy the $):

```
$ git checkout master
$ git pull origin master
$ sudo rm -R node_modules
$ sudo npm install -g yarn
$ yarn install
$ node database/reindex_elastic.js
$ ./node_modules/.bin/webpack --config webpack.production.config.js
```
This should make sure that:
- you are in the right branch
- everything is up to date
- that node modules are freshly installed with the newest version of yarn
- your elasticsearch is correctly indexed
- the build is using the suported webpack version (in case your global version is older or newer than the one required for the project).

After all this, please report back the results. Best regards,
Rafa.

**Comment by chrisha88** [comment] 2018-03-14 14:10
Hi Rafa,

Please see below responses for the codes run on the Terminal.
$ git checkout master
M	app/api/config/mailer.js
M	app/react/config.js
Already on 'master'
Your branch is up-to-date with 'origin/master'.

$ git pull origin master
From https://github.com/huridocs/uwazi
 * branch            master     -> FETCH_HEAD
Already up-to-date.

$ sudo rm -R node_modules

$ sudo npm install -g yarn
/usr/bin/yarn -> /usr/lib/node_modules/yarn/bin/yarn.js
/usr/bin/yarnpkg -> /usr/lib/node_modules/yarn/bin/yarn.js
/usr/lib
└── yarn@1.5.1 

$ yarn install
yarn install v1.5.1
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.2: The platform "linux" is incompatible with this module.
info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "babel-istanbul-loader > babel-loader@6.2.10" has incorrect peer dependency "webpack@1 || 2 || ^2.1.0-beta || ^2.2.0-rc".
warning " > eslint-plugin-react@7.3.0" has incorrect peer dependency "eslint@^3.0.0 || ^4.0.0".
warning " > sass-loader@3.2.3" has incorrect peer dependency "webpack@^1.12.6 || ^2.1.0-beta".
[4/4] Building fresh packages...
Done in 45.22s.

$ node database/reindex_elastic.js
module.js:471
    throw err;
    ^

Error: Cannot find module '/home/dell/uwazi/database/reindex_elasticsearch'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:496:3

**Comment by RafaPolit** [comment] 2018-03-19 15:23
Were all the commands run inside the project's root folder?  The first commands are directory-independent.  The last command that failed is directory dependent.

Also, it would be useful the output of the following commands:

```
$ node --version
$ curl localhost:9200
$ ps aux | grep mongo
```

**Comment by chrisha88** [comment] 2018-03-20 14:08
Hi Rafa,
I ran all the previous codes in the uwazi directory.

The outcome of the last 3 codes are this..
$ node --version
v6.12.3

$ curl localhost:9200
{
  "name" : "r8Xp_4G",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "4pBa56oxT2K-9cu82e7lzA",
  "version" : {
    "number" : "5.6.0",
    "build_hash" : "781a835",
    "build_date" : "2017-09-07T03:09:58.087Z",
    "build_snapshot" : false,
    "lucene_version" : "6.6.0"
  },
  "tagline" : "You Know, for Search"
}

$ ps aux | grep mongo
mongodb   8958  0.1  0.9 961220 39376 ?        Ssl  16:55   0:14 /usr/bin/mongod --config /etc/mongod.conf
dell     10143  0.0  0.0  14228  1056 pts/2    S+   19:32   0:00 grep --color=auto mongo

**Comment by RafaPolit** [comment] 2018-03-20 18:00
Everything looks OK.

We are going to have to schedule a call in order to do faster troubleshooting sharing screen and trying a couple of things.

Lets try and find a good schedule.  Perhaps due to time zones, it would be easier to find common hours with @daneryl .  I'm in the GMT -5:00 timezone.

**Comment by chrisha88** [comment] 2018-03-21 06:53
Hi Rafael,

I will be available this Friday at the SACLS. It is better if we can schedule the call on that day.

**Comment by RafaPolit** [comment] 2018-03-22 16:20
What time frame would be best for you?  Anytime after 2pm GMT is OK by me.

**Comment by chrisha88** [comment] 2018-03-22 16:25
Not possible to do tomorrow as it'll be after 7:30pm Sri Lankan time. I can connect to the server through TeamViewer on my machine and can I take the call?

**Comment by RafaPolit** [comment] 2018-03-24 18:09
@chrisha88 , there is an issue with a babel path resolver which may be the cause of these issues.

We have identified the problem, and have corrected it on the upcoming release.  We need to fine-tune a data migration which is required for the new version, and then everything should work as expected.

This should not take longer than Monday or Tuesday.  As soon as the update is released, I'll write back with new instructions which also will hopefully be much simpler.

Thanks for your patience.
Rafa.

**Comment by chrisha88** [comment] 2018-04-02 16:27
Can I do a Git pull?

**Comment by txau** [comment] 2018-05-23 03:02
Hello @chrisha88. I hope you managed to make your instance work. I'm closing this issue for the time being. Please reopen or create a new one if you need further support.

**Closed by txau** 2018-05-23 03:02 UTC
