### ISSUE TITLE
Published items have two entries in Elastic Search index: one for the published one, one for the unplished one

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#801] opened 2017-02-10 20:42 UTC
Entities or documents that are uploaded or created in uploads and the published, get two entries in the Elastic Search index: one for the one published, and one for the unpublished one.

This hasn't been much of an issue (other than probably growth over time and performance issues), but now that we will be using the Elastic Index for other searches, this is a problem, as we are getting duplicated items when searching.

@konzz , can you please confirm this? Thanks.
Rafa.

**Comment by konzz** [comment] 2017-02-16 13:41
@RafaPolit Can't reproduce this, are you sure it is about published / unpublished and not one per language?

**Comment by konzz** [comment] 2017-02-20 10:59
@RafaPolit I could replicate it, but it's probably fixed with the change to mongodb, @daneryl will confirm this.

**Comment by konzz** [comment] 2017-07-02 22:43
Fixed

**Closed by konzz** 2017-07-02 22:43 UTC
Labels: Bug, Development, In progress
