### ISSUE TITLE
Problem with facets when I set a collection as home page

### ISSUE THREAD

**Issue by danieldesposito** [huridocs/uwazi#1410] opened 2017-12-11 19:03 UTC
When I set my collection as home page in the collection settings, the facets are no longer active, I click on them but no filtering happens: https://nonprofit.uwazi.io
Actually most of the other hyperlinks don't work either.

**Comment by konzz** [comment] 2018-02-05 13:17
Hi @danieldesposito can you provide more information on how to reproduce it?
How do you set the collection as home page in the collection settings?

**Comment by txau** [comment] 2018-05-23 03:50
@danieldesposito tried to reproduce the problem without luck. Looks like this has already been fixed. Closing for now, please reopen if the problem persists.

**Closed by txau** 2018-05-23 03:50 UTC
Labels: Bug, Priority: Low
