### ISSUE TITLE
Missplaced "add supporting file" button

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#3556] opened 2021-03-23 15:29 UTC
![image](https://user-images.githubusercontent.com/489831/112172379-4869c000-8bba-11eb-87cd-56fd535a281f.png)

**Comment by simonfossom** [comment] 2021-03-23 16:28
No, it's by design. We should at some point move "upload documents" button to the right of the "Primary Documents" title for consistency. 

![screen01](https://user-images.githubusercontent.com/8134850/112181587-dc5c7b80-8bfc-11eb-98b5-3fbb67aa0a03.png)

**Comment by nwyu** [comment] 2021-03-23 18:47
Closing this issue in favor of #3557.

**Closed by nwyu** 2021-03-23 18:47 UTC

**Comment by txau** [comment] 2021-03-24 13:34
@simonfossom having it on top makes sense, but having the button 700px away from the title not so much. Maybe the rightful place is besides the title?

**Comment by simonfossom** [comment] 2021-03-26 13:34
Yes, we've addressed it here: #3569
