### ISSUE TITLE
Library filters fail at specific url combinations

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#667] opened 2016-11-23 17:16 UTC
### Steps to replicate
- Reload the app in the home directory
- Go to library
- Filter 'cases'
- Click on the 'Uwazi' link
- Filter 'cases'
- Filter by country 

The fail is listed and the server throws errors.

**Comment by konzz** [comment] 2017-05-12 15:29
@RafaPolit Can't reproduce this, should we close this issue since I did not see the url fail in long time?

**Closed** 2017-07-02 22:20 UTC
Labels: Bug, Development
