### ISSUE TITLE
Text selections do not get spaces at the end of lines resulting in word concatenation

### ISSUE THREAD

**Issue by HSips** [huridocs/uwazi#1645] opened 2018-05-31 06:55 UTC
Oh IHRDA instance, when one does a connection to a sub-paragraph, in this case, Art 12.1 or 12(1) of the African Charter, on the connection column, it shows as Art. 121.
Kindly advice. See screen shot below
![inkedscreen shot 2018-05-30 at 3 10 14 pm_li](https://user-images.githubusercontent.com/22650647/40766584-9da4782a-64b8-11e8-9808-70c4438d9948.jpg)

**Comment by txau** [comment] 2018-05-31 15:35
This is a known issue in Uwazi. Its caused by the way PDFs are converted into plain text, not computing carriage returns at the end of lines as returns or blank spaces. This is being worked on a PDF improvement branch, but it will take a while to be fixed.

**Comment by vorburger** [comment] 2019-10-02 17:21
Assuming they are public, would you be able to post links to a few example problematic PDFs here?

**Comment by txau** [comment] 2022-08-26 15:01
Fixed with the recent upgrade of PDF.js. To be deployed soon.

**Closed by txau** 2022-08-26 15:01 UTC
Labels: Bug :lady_beetle:, Priority: Medium
