### ISSUE TITLE
When in the upoad section, the 'X' button in the top right corner of the sidebar doesn't do anything

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#923] opened 2017-04-14 18:11 UTC
I noticed this behavior in a few places, such as when you are looking at a document in your uploads section:
![image](https://cloud.githubusercontent.com/assets/354426/25051746/30cd83e4-211c-11e7-8bc3-69441ef40d72.png)

Seems to work fine in the library section. 
Using firefox.

**Comment by RafaPolit** [comment] 2017-04-28 14:10
Cannot reproduce now that uploads and library are merged.  Either that or something else probably fixed this behavior.

**Closed by RafaPolit** 2017-04-28 14:10 UTC
Labels: Bug, In progress, Sprint
