### ISSUE TITLE
Several bugs in multidates 

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#1180] opened 2017-07-30 01:27 UTC
In CEJIL they added a multidate field to their Medida Provisional entity.

- JS error when opening the side panel in library.
- JS error when saving in entity view.
- Timelines no working.

![screen shot 2017-07-29 at 19 23 19](https://user-images.githubusercontent.com/489831/28749900-e4be50ca-7493-11e7-829b-78bc7dd6f682.png)
![screen shot 2017-07-29 at 19 22 21](https://user-images.githubusercontent.com/489831/28749901-e4c51d60-7493-11e7-9f43-68be1d6a07f0.png)

**Comment by kjantin** [comment] 2017-07-31 15:11
From sprint conversation: this could be related to other existing issues. Moving to sprint, will investigate.

**Comment by RafaPolit** [comment] 2017-07-31 17:07
This probably has nothing to do with Multidate.

Sounds related to #1126.  Checking this out.

**Comment by RafaPolit** [comment] 2017-07-31 18:10
Issue is not related to #1126 (which is fixed), further researching the problem.

**Comment by RafaPolit** [comment] 2017-07-31 20:04
I can reproduce this locally, there is some error with the data types for this newly created fields and arrays are being defaulted as empty strings.

**Comment by RafaPolit** [comment] 2017-08-01 00:12
The main problem was that elastic search's index had grown beyond the default limit of 1000 fields.

This happened because the pdfInfo (which is stored in Mongo as an object with a key for each page) was getting indexed with one field per page.  So we had 204 fields belonging to page numbers.  Those indexes where being triple-indexed due to our new sorting fields, so this pushed the limit over 1000 fields.

I have removed the pdfInfo from the elastic index, but we need to purge this further.

**Closed by RafaPolit** 2017-08-01 00:12 UTC
Labels: Bug, In progress, Sprint

**Comment by txau** [comment] 2017-08-01 14:45
@RafaPolit Timelines are not showing the dates that they are supposed to show: https://cejil.uwazi.io/es/entity/vlgcm2oi9owbc7gp8613e4s4i
