### ISSUE TITLE
Changing admin password on new installation locks out of account

### ISSUE THREAD

**Issue by yuvadm** [huridocs/uwazi#3367] opened 2020-12-14 13:59 UTC
After installing a new production instance, it is possible to log on with default credentials.

However, when following that advice :wink: and going to actually change the password in the Account Settings page, a new password is entered and Update is clicked.

While a success prompt is shown, the server logs show the following line:

```
DeprecationWarning: Mongoose: `findOneAndUpdate()` and `findOneAndDelete()` without the `useFindAndModify` option set to false are deprecated. See: https://mongoosejs.com/docs/deprecations.html#findandmodify
```

Once the admin user logs out, neither of the passwords work, not the default one, nor the new password that was supposedly updated successfully.

This is running version `1.16.0`. I'm checking now to verify against `1.17.0` which was just now released.

**Comment by yuvadm** [comment] 2020-12-14 14:18
Still happens on `1.17.0`

**Comment by RafaPolit** [comment] 2020-12-14 14:41
Thanks for the report. 

The `DeprecationWarning` is just a warning at this point, it should not be reason for this failure.  We can try to reproduce this issue on our dev environment.  If we can reproduce it, we will upgrade this issue to a bug.  If we can't, I'll report back with some places you can check to get this working as expected.

**Comment by RafaPolit** [comment] 2020-12-15 16:41
Thanks again for the report.  We have found the issue, it is a bug on our side.   We have a Pull Request in the process with the fix. 
 It will be merged into the `master` branch on v1.18 or v1.19.

For further reference, the issue is being developed in #3360

**Comment by yuvadm** [comment] 2020-12-15 21:12
@RafaPolit Great to hear! Looking forward to the fix and release.

**Comment by RafaPolit** [comment] 2021-01-05 16:04
@yuvadm This issue is finally fixed.  Please, upgrade to https://github.com/huridocs/uwazi/releases/tag/1.19.1 .

You would need to login, and change the password.  If you were locked out, you can reset your password now normally.  If you are unable, please reach out to me, I can help to unlock your account.

**Closed** 2021-03-16 08:53 UTC
Labels: Bug
