### ISSUE TITLE
Document TOC is not scrolling to its location.

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#700] opened 2016-12-07 19:14 UTC
If you create several TOCs and try to click-scroll to its location, the document does not scroll.

**Comment by konzz** [comment] 2016-12-27 18:23
@RafaPolit Can't reproduce, could you add steps to reproduce it or check if a previous update fixed it?

**Comment by txau** [comment] 2017-01-09 15:19
Closing. Can't reproduce.

**Closed by txau** 2017-01-09 15:19 UTC
Labels: bug, dev, NEW
