### ISSUE TITLE
Error exporting over 350 entities with filters applied

### ISSUE THREAD

**Issue by JuliMirandaCELS** [huridocs/uwazi#4120] opened 2022-01-05 16:34 UTC
Our instance yields an error while exporting a certain number of entities (around 350, not always the exact same number) in bulk. This happens only when filters are applied, but not when an entire template containing over 30,000 entities is exported.

![print Uwazi 2](https://user-images.githubusercontent.com/97182901/148253797-61e2aa3c-c065-4c9c-8ae9-23ed80471368.png)

![Print Uwazi](https://user-images.githubusercontent.com/97182901/148253614-e50b997a-06ce-451c-ae1f-ae5a09742986.png)

**Comment by fnocetti** [comment] 2022-09-06 14:12
Couldn't reproduce this. Closing since the issue is rather old and we've done some work in the search side.
Feel free to reopen if this is still a problem.

**Closed by fnocetti** 2022-09-06 14:12 UTC
Labels: Bug :lady_beetle:, Priority: High, Backend 💾
