### ISSUE TITLE
Unresponsive script 

### ISSUE THREAD

**Issue by HSips** [huridocs/uwazi#991] opened 2017-05-13 09:29 UTC
I keep getting unresponsive script message. See screenshot below
![unresponsive script](https://cloud.githubusercontent.com/assets/22650647/26024317/b2398a6e-37d7-11e7-8bdb-9a12f32e1598.png)

**Comment by daneryl** [comment] 2017-05-16 12:19
@HSips tried to open the file on the screenshot with many slow devices and its working for me even in my iphone 4, are you doing any other thing apart from opening the 282 document ?? can not replicate.

**Comment by kjantin** [comment] 2017-06-20 14:49
Cannot reproduce per @HSips , closing for now and will reopen if this happens again.

**Closed by kjantin** 2017-06-20 14:49 UTC
Labels: Bug, Next
