### ISSUE TITLE
Public Form on private instances logs out user (7pts)

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#3463] opened 2021-02-08 21:09 UTC
To reproduce:
- create a private instance with a page with a (remote?) public form
- create a menu to that page (not sure this is required)
- login
- submit the form

Refresh the page, you are logged out.

**Comment by nwyu** [comment] 2021-04-09 18:54
We are unable to reproduce this issue. Closing.

**Closed by nwyu** 2021-04-09 18:54 UTC
Labels: Bug, Status: Sprint
